### ISSUE TITLE
Concurrency exception

### ISSUE THREAD

**Issue by lbarman** [dedis/prifi#151]
```
fatal error: concurrent map writes

goroutine 17028 [running]:
1 : (                             services.(*churnHandler).tryStartProtocol: 297) - Enough participants ( 5 clients and 1 trustees), but no handler to start.
runtime.throw(0x8ceae9, 0x15)
	/usr/lib/golang/src/runtime/panic.go:566 +0x95 fp=0xc4c4826b50 sp=0xc4c4826b30
runtime.mapassign1(0x84a4a0, 0xc4d9577e90, 0xc4c4826d10, 0xc4c4826c88)
	/usr/lib/golang/src/runtime/hashmap.go:458 +0x8ef fp=0xc4c4826c38 sp=0xc4c4826b50
github.com/lbarman/prifi/sda/services.(*churnHandler).handleConnection(0xc420133180, 0xc4aaca4a80)
	/d/go/src/github.com/lbarman/prifi/sda/services/churn.go:222 +0x595 fp=0xc4c4826ed0 sp=0xc4c4826c38
github.com/lbarman/prifi/sda/services.(*ServiceState).HandleConnection(0xc4200e0960, 0xc4aaca4a80)
	/d/go/src/github.com/lbarman/prifi/sda/services/prifi.go:78 +0x196 fp=0xc4c4826f68 sp=0xc4c4826ed0
github.com/lbarman/prifi/sda/services.(*ServiceState).HandleConnection-fm(0xc4aaca4a80)
	/d/go/src/github.com/lbarman/prifi/sda/services/service.go:88 +0x34 fp=0xc4c4826f88 sp=0xc4c4826f68
gopkg.in/dedis/onet.v1/network.(*defaultProcessor).Process(0xc420026190, 0xc4aaca4a80)
	/d/go/src/gopkg.in/dedis/onet.v1/network/dispatch.go:125 +0x33 fp=0xc4c4826fa0 sp=0xc4c4826f88
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4c4826fa8 sp=0xc4c4826fa0
created by gopkg.in/dedis/onet.v1/network.(*RoutineDispatcher).Dispatch
	/d/go/src/gopkg.in/dedis/onet.v1/network/dispatch.go:116 +0xdd
```

**Comment by lbarman** [comment]
Fixed 33da5021ddf69f5d09c028654f6ad8fffd395484
