### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by lbarman** [dedis/prifi#173]
*Description:* start 2 clients, 1 relay, 1 trustee, socks-server, query `epfl.ch` (possibly multiple times / multiple concurrent queries on the browser)

```
E : (                       main.HandleClient: 115) - Socks Server : Version is  178  only 5 is supported.
panic: Invalid message, 57217 msg, but size is 5000
goroutine 40 [running]:
github.com/lbarman/prifi/prifi-lib/log.DecodeLatencyMessages(0xc420392b19, 0x1388, 0x1388, 0x0, 0x1577, 0xc420587168)
    /Users/junchen/Developer/go/src/github.com/lbarman/prifi/prifi-lib/log/latencymsg.go:97 +0x2cd
github.com/lbarman/prifi/prifi-lib/client.(*PriFiLibClientInstance).ProcessDownStreamData(0xc42013cf20, 0x1577, 0x1, 0xc420392b19, 0x1388, 0x1388, 0x0, 0xc4201d6318, 0xc4201d6320)
    /Users/junchen/Developer/go/src/github.com/lbarman/prifi/prifi-lib/client/client.go:219 +0xea0
github.com/lbarman/prifi/prifi-lib/client.(*PriFiLibClientInstance).Received_REL_CLI_DOWNSTREAM_DATA(0xc42013cf20, 0x1577, 0x1, 0xc420392b19, 0x1388, 0x1388, 0x0, 0xc420587648, 0xc4201f2b00)
    /Users/junchen/Developer/go/src/github.com/lbarman/prifi/prifi-lib/client/client.go:165 +0x417
github.com/lbarman/prifi/prifi-lib/client.(*PriFiLibClientInstance).ReceivedMessage(0xc42013cf20, 0x4496d80, 0xc4201e8de0, 0x40103ef, 0x4496d80)
    /Users/junchen/Developer/go/src/github.com/lbarman/prifi/prifi-lib/client/init.go:159 +0x643
github.com/lbarman/prifi/prifi-lib.(*PriFiLibInstance).ReceivedMessage(0xc4201e52c0, 0x4496d80, 0xc4201e8de0, 0xc4201e8de0, 0x0)
    /Users/junchen/Developer/go/src/github.com/lbarman/prifi/prifi-lib/prifi.go:90 +0x4c
github.com/lbarman/prifi/sda/protocols.(*PriFiSDAProtocol).Received_REL_CLI_DOWNSTREAM_DATA(0xc420220420, 0xc4201f1900, 0x1577, 0x1, 0xc420392b19, 0x1388, 0x1388, 0x0, 0xc4200cb401, 0x0)
    /Users/junchen/Developer/go/src/github.com/lbarman/prifi/sda/protocols/message_binders.go:17 +0x80
github.com/lbarman/prifi/sda/protocols.(*PriFiSDAProtocol).Received_REL_CLI_DOWNSTREAM_DATA-fm(0xc4201f1900, 0x1577, 0x1, 0xc420392b19, 0x1388, 0x1388, 0x0, 0x0, 0x0)
    /Users/junchen/Developer/go/src/github.com/lbarman/prifi/sda/protocols/protocol.go:187 +0x51
reflect.Value.call(0x4435a80, 0xc42037a970, 0x13, 0x44da3c7, 0x4, 0xc420587c20, 0x1, 0x1, 0x4496d80, 0xc4200bf4c0, ...)
    /usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x4435a80, 0xc42037a970, 0x13, 0xc420587c20, 0x1, 0x1, 0x199, 0xc420587b50, 0x4012789)
    /usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:308 +0xa4
gopkg.in/dedis/onet%2ev1.(*TreeNodeInstance).dispatchHandler(0xc420189d40, 0xc4200c8178, 0x1, 0x1, 0x3, 0x1)
    /Users/junchen/Developer/go/src/gopkg.in/dedis/onet.v1/treenode.go:336 +0x3b0
gopkg.in/dedis/onet%2ev1.(*TreeNodeInstance).dispatchMsgToProtocol(0xc420189d40, 0xc4202623c0, 0x3, 0xc420022fb0)
    /Users/junchen/Developer/go/src/gopkg.in/dedis/onet.v1/treenode.go:456 +0x4bf
gopkg.in/dedis/onet%2ev1.(*TreeNodeInstance).dispatchMsgReader(0xc420189d40)
    /Users/junchen/Developer/go/src/gopkg.in/dedis/onet.v1/treenode.go:424 +0x1fe
created by gopkg.in/dedis/onet%2ev1.newTreeNodeInstance
    /Users/junchen/Developer/go/src/gopkg.in/dedis/onet.v1/treenode.go:86 +0x201
exit status 2
```

**Comment by lbarman** [comment]
Fixed 123c2ab8d0b883d3748ae9f3558a59ebf3faeab2
